### ISSUE TITLE
gpu.js version

### ISSUE THREAD

**Issue by robertleeplummerjr** [Web-Sight/WebSight#16]
If you are demoing next generation means of scripting and processing, why not push the limit and add gpu processing?

http://gpu.rocks/

**Comment by BrianJFeldman** [comment]
This definitely seems like something right up the alley of what we set out to accomplish with the project, but we never got into hardware optimization. I'm curious how the library would perform in a webworker without access to WebGL, but when I find more time to revisit the project, I will definitely be looking into this library.
