### ISSUE TITLE
cv.CascadeClassifier is not a constructor

### ISSUE THREAD

**Issue by Mte90** [Web-Sight/WebSight#17]
![screenshot_20170914_002447](https://user-images.githubusercontent.com/403283/30403716-4049a016-98e3-11e7-90d1-2c015d383538.png)
Using Firefox Nightly on Linux I got this error.
Also the page is very slow to load and actually asm.js is not working, maybe add a progress icon to show that is loading the resource will be helpful. Initially I was thinking that wasn't working so I refreshed few times.

**Comment by BrianJFeldman** [comment]
Thanks for the heads up! This is a known issue that occurs when the web workers take too long to load their respective asm or wasm code. Our goal was to always add a custom load event that we could fire to start each of the formats, but we just ran out of time. 

I'm closing the issue for now, but if you'd like to submit a PR with the custom event, I'd love to add it to the codebase!

**Comment by odedsesame** [comment]
Brian, any chance you can give a pointer to how to fix this issue? For others finding this post?

Many thanks!

**Comment by BrianJFeldman** [comment]
We had intended to eventually setup a loading state that better made use of web worker API, but I haven't been using web workers in my newest projects so I'm going to be less helpful than I believe either of us would hope for. 

I was hopeful about PeterJensen's `onRuntimeInitialized` approach that was merged above (in #19) but if that's not working for you locally than I'd continue to explore the WebWorker API for on-load events to fire the initial message.

**Comment by odedsesame** [comment]
onRuntimeInitialized worked for me eventually. I had to add it myself though, wasn't pulled from the repo.

Thanks for helping!!
Best,
Oded
