### ISSUE TITLE
Help building opencv.js with wasm?

### ISSUE THREAD

**Issue by sid-kap** [Web-Sight/WebSight#18]
Hi, I was trying to build the wasm version of opencv, and I was running into some problems. Could someone who worked on this explain how you managed to build opencv.wasm? (Or link me to somewhere where I can download the built version?)

**Comment by sid-kap** [comment]
Never mind, this was fixed by https://github.com/opencv/opencv/issues/10760

**Comment by simtrax** [comment]
@sid-kap I'm curious how you managed to build the opencv wasm file. Where you able to compile it? And in that case how did you do it?

**Comment by sid-kap** [comment]
Yes, I was! In an environment with all the correct dependencies (emscripten, binaryen, python2, cmake, opencl headers), I ran the command
```sh
python ./platforms/js/build_js.py build_wasm --build_wasm --emscripten_dir=<location of emscripten>
```
What errors are you getting?

**Comment by simtrax** [comment]
`python ./platforms/js/build_js.py build_wasm --build_wasm
Args: Namespace(build_dir='build_wasm', build_doc=False, build_test=False, build_wasm=True, clean_build_dir=False, config_only=False, emscripten_dir='<path to emscripten/emsdk/emscripten/1.38.4>', enable_exception=False, opencv_dir='<my-open-cv-dir>', skip_config=False)
Check dir <my-open-cv-dir>/build_wasm (create: True, clean: False)
Check dir <my-open-cv-dir> (create: False, clean: False)
Check dir <path to emscripten/emsdk/emscripten/1.38.4> (create: False, clean: False)
Traceback (most recent call last):
  File "./platforms/js/build_js.py", line 216, in <module>
    builder = Builder(args)
  File "./platforms/js/build_js.py", line 85, in __init__
    self.emcc_version = determine_emcc_version(self.emscripten_dir)
  File "./platforms/js/build_js.py", line 63, in determine_emcc_version
    m = re.match(r'^emcc.*(\d+\.\d+\.\d+)', ret, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object`

Can't seem to get around this problem. Seems to be more related to python than the build process.

This is the output from emcc --version
`emcc (Emscripten gcc/clang-like replacement) 1.38.4 (commit a4474e59db658cea570c78254fa71119cf688db5)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by sid-kap** [comment]
The problem is that the build code works only in python2, and python3 is being used.
