### ISSUE TITLE
The weblink is not working

### ISSUE THREAD

**Issue by anilbhattaraitoronto** [Web-Sight/WebSight#20]
Hello,
I have been trying to go to your website, but it seems to have been either broken or offline.

Thank you for this awesome project, in any case. 

Anil

**Comment by MarkGeeRomano** [comment]
Hi @anilbhattaraitoronto , sorry to just catch this now. We pretty recently stopped paying the annual fee to host the page. If you pull it down locally, it should work though. I forked this repo a while ago, if this doesn't work, try running my fork.

**Comment by styfle** [comment]
Maybe try creating a Dockerfile and publish to https://zeit.co/now since they have mostly free hosting for open source.
