### ISSUE TITLE
demo sight is not working.

### ISSUE THREAD

**Issue by Niko-La** [Web-Sight/WebSight#21]
http://websightjs.com

The demo site is not working.
Maybe we can host it on a SSG like netlify or now! as they are free.

**Comment by jfoote** [comment]
websightjs.com now appears to be serving shady content. I'd recommend removing the link from the documentation or similar if there is not intent to use it going forward.

**Comment by MarkGeeRomano** [comment]
We stopped hosting it a while ago. Feel free to put it up if you'd like!

@jfoote thanks for the note, going to remove it.

**Comment by brianpeiris** [comment]
FYI, https://github.com/Web-Sight still links to the shady websightjs.com

![image](https://user-images.githubusercontent.com/79419/59536066-84310b00-8ea7-11e9-8d4a-9bd9863a0bda.png)
