### ISSUE TITLE
How to run this demo locally?

### ISSUE THREAD

**Issue by TedaLIEz** [Web-Sight/WebSight#22]
I watched your talks on [youtube](https://www.youtube.com/watch?v=ysFJHpS-O08) and I want to have a look at your demo. Through the website seems to be out of date, I think I may have a try on my local machine. I tried with `python -m SimpleHTTPServer` in `src` folder, but nothing happened after uploading an image of a human face, neither with the video-demo. What am I missing?

**Comment by berooney** [comment]
Hi @TedaLIEz , It require a https connection to canable run Wams. So you can use ngrok to create a https connection forward python -m SimpleHTTPServer port.

**Comment by ezerway** [comment]
Hi @TedaLIEz  , It require a https connection to canable run Wams. So you can use ngrok to create a https connection forward python -m SimpleHTTPServer port.

**Comment by TedaLIEz** [comment]
@ezerway Thanks, I'll give it a try.
